spring.application.name=account-service

spring.datasource.url=jdbc:postgresql://localhost:5432/accountsdb
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=kpUrn5hVXAmlqxIZPh5W7yMM/WseFNF9QwoM48F8Su4=

server.port=8090