spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=kpUrn5hVXAmlqxIZPh5W7yMM/WseFNF9QwoM48F8Su4=
jwt.expiration=3600000

server.port=8081

